
CC  = icc
CFLAGS = -O

all:	hello_world_serial

clean:
	rm -f *.[oadD] *.[mM][oO][dD] hello_world_serial

hello_world_serial:	hello_world_serial.c
	${CC} ${CFLAGS} -o hello_world_serial hello_world_serial.c

